name: Deploy API to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish API
      run: dotnet publish ./api/SaunaBookingApi.csproj -c Release -o ./publish

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.HETZNER_DEPLOY_KEY }}

    - name: Deploy to Hetzner via rsync
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./publish/ saunadeploy@${{ secrets.HETZNER_HOST }}:/home/saunadeploy/api/

    - name: (Optional) Restart API via SSH
      run: |
        ssh -o StrictHostKeyChecking=no saunadeploy@${{ secrets.HETZNER_HOST }} << 'EOF'
          # You can later replace this with: sudo systemctl restart sauna-api
          echo "Deploy complete on $(hostname) at $(date)"
        EOF