name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'client/**'
      - '.github/workflows/deploy_frontend.yaml'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Clean previous frontend publish
      run: rm -rf ./client_publish

    - name: Publish Blazor WASM
      run: dotnet publish ./client/client.csproj -c Release -o ./client_publish /p:BaseHref="/sauna/"

    - name: Add SSH key for Hetzner
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.HETZNER_DEPLOY_KEY }}

    - name: Deploy frontend to Hetzner
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./client_publish/wwwroot/ saunadeploy@${{ secrets.HETZNER_HOST }}:/var/www/mymh.dev/public_html/sauna/